Updated README.md to reflect version 3.0.0
npwalker/pe_metric_curl_cron_jobs pull request #10
Opened 2017-03-14 21:13 UTC by jarretlavallee

Fixes issue #8

Prior to this commit the *README.md* showed information about v2.x, which
is no longer accurate with v3.0.0. This update provides new output and
updated commands for the current state of the module in the *README.md*. 

Since there is a dependency on *puppetlabs-stdlib*, I added `".:$(puppet config print modulepath)"` as the module path for the puppet apply. This should hopefully exclude users from having to download the *puppetlabs-stdlib* module locally to */tmp*. I figure that most customers will have the *stdlib* module already installed, but the *README.md* can easily changed to show how to pull the *puppetlabs-stdlib* module into */tmp* instead if that is a better approach.

2017-03-14 23:58 UTC, npwalker commented on README.md
> +- [How to use](#how-to-use)
not obvious but I'm generating this from gh-md-toc.  https://github.com/ekalinin/github-markdown-toc

2017-03-15 16:54 UTC, jarretlavallee commented
TOC has been updated with * instead of - for the bullet points and better nesting.

2017-03-18 05:41 UTC, reidmv requested changes
This is great! I love it when people update the docs. :)

Dropped a few comments about missing ~`puppet_server`~ => `puppetserver` conversions. Otherwise, all 👍 !

2017-03-18 05:41 UTC, reidmv commented on README.md
> +  puppet_server_hosts => [
this should be `puppetserver` (current API) instead of `puppet_server` (deprecated API)

2017-03-18 05:41 UTC, reidmv commented on README.md
> +When you classify a PuppetDB node you would set `$puppet_server_metrics_ensure` to `absent`.
~`puppet_server`~ => `puppetserver`

2017-03-20 14:40 UTC, merged